language: node_js
node_js:
  - "node"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm ci
  - npm run build

script: 
  - npm test

after_success:
  - npm pack

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "{tofulite}-*.tgz"
    skip_cleanup: true
    on:
      tags: true
