language: node_js
node_js:
  - "node"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm ci
  - npm run build

script: 
  - npm test

after_success:
  - npm pack

deploy:
  - provider: releases
    edge: true
    token: $GITHUB_TOKEN
    file: "{tofulite}-*.tgz"
    on:
      tags: true
  - provider: npm
    edge: true
    api_token: $NPM_TOKEN
    on:
      tags: true
